name: sample-nextjs
services:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: ionelcucu/sample-nextjs
    name: sample-nextjs
